/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarTrendsRouteImport } from './../routes/_sidebar/trends'
import { Route as SidebarTrackerRouteImport } from './../routes/_sidebar/tracker'
import { Route as SidebarStudentsRouteImport } from './../routes/_sidebar/students'
import { Route as SidebarSimulatorRouteImport } from './../routes/_sidebar/simulator'
import { Route as SidebarResearchFinanceRouteImport } from './../routes/_sidebar/research-finance'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarPlatformRouteImport } from './../routes/_sidebar/platform'
import { Route as SidebarOutcomesRouteImport } from './../routes/_sidebar/outcomes'
import { Route as SidebarInterventionRouteImport } from './../routes/_sidebar/intervention'
import { Route as SidebarGovernanceRouteImport } from './../routes/_sidebar/governance'
import { Route as SidebarFinancialHealthRouteImport } from './../routes/_sidebar/financial-health'
import { Route as SidebarFinanceCopilotRouteImport } from './../routes/_sidebar/finance-copilot'
import { Route as SidebarFinanceActionsRouteImport } from './../routes/_sidebar/finance-actions'
import { Route as SidebarFinanceRouteImport } from './../routes/_sidebar/finance'
import { Route as SidebarFacultyRouteImport } from './../routes/_sidebar/faculty'
import { Route as SidebarEnrollmentFinanceRouteImport } from './../routes/_sidebar/enrollment-finance'
import { Route as SidebarDashboardRouteImport } from './../routes/_sidebar/dashboard'
import { Route as SidebarCoursesRouteImport } from './../routes/_sidebar/courses'
import { Route as SidebarCopilotRouteImport } from './../routes/_sidebar/copilot'
import { Route as SidebarAnalyticsRouteImport } from './../routes/_sidebar/analytics'
import { Route as SidebarAlertsRouteImport } from './../routes/_sidebar/alerts'
import { Route as SidebarAiActionsRouteImport } from './../routes/_sidebar/ai-actions'
import { Route as SidebarAdvisorAgentRouteImport } from './../routes/_sidebar/advisor-agent'
import { Route as SidebarStudentsStudentIdRouteImport } from './../routes/_sidebar/students.$studentId'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarTrendsRoute = SidebarTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarTrackerRoute = SidebarTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarStudentsRoute = SidebarStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSimulatorRoute = SidebarSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarResearchFinanceRoute = SidebarResearchFinanceRouteImport.update({
  id: '/research-finance',
  path: '/research-finance',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarPlatformRoute = SidebarPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarOutcomesRoute = SidebarOutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarInterventionRoute = SidebarInterventionRouteImport.update({
  id: '/intervention',
  path: '/intervention',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGovernanceRoute = SidebarGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarFinancialHealthRoute = SidebarFinancialHealthRouteImport.update({
  id: '/financial-health',
  path: '/financial-health',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarFinanceCopilotRoute = SidebarFinanceCopilotRouteImport.update({
  id: '/finance-copilot',
  path: '/finance-copilot',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarFinanceActionsRoute = SidebarFinanceActionsRouteImport.update({
  id: '/finance-actions',
  path: '/finance-actions',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarFinanceRoute = SidebarFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarFacultyRoute = SidebarFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarEnrollmentFinanceRoute =
  SidebarEnrollmentFinanceRouteImport.update({
    id: '/enrollment-finance',
    path: '/enrollment-finance',
    getParentRoute: () => SidebarRouteRoute,
  } as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarCoursesRoute = SidebarCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarCopilotRoute = SidebarCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAnalyticsRoute = SidebarAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAlertsRoute = SidebarAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAiActionsRoute = SidebarAiActionsRouteImport.update({
  id: '/ai-actions',
  path: '/ai-actions',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAdvisorAgentRoute = SidebarAdvisorAgentRouteImport.update({
  id: '/advisor-agent',
  path: '/advisor-agent',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarStudentsStudentIdRoute =
  SidebarStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => SidebarStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor-agent': typeof SidebarAdvisorAgentRoute
  '/ai-actions': typeof SidebarAiActionsRoute
  '/alerts': typeof SidebarAlertsRoute
  '/analytics': typeof SidebarAnalyticsRoute
  '/copilot': typeof SidebarCopilotRoute
  '/courses': typeof SidebarCoursesRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/enrollment-finance': typeof SidebarEnrollmentFinanceRoute
  '/faculty': typeof SidebarFacultyRoute
  '/finance': typeof SidebarFinanceRoute
  '/finance-actions': typeof SidebarFinanceActionsRoute
  '/finance-copilot': typeof SidebarFinanceCopilotRoute
  '/financial-health': typeof SidebarFinancialHealthRoute
  '/governance': typeof SidebarGovernanceRoute
  '/intervention': typeof SidebarInterventionRoute
  '/outcomes': typeof SidebarOutcomesRoute
  '/platform': typeof SidebarPlatformRoute
  '/profile': typeof SidebarProfileRoute
  '/research-finance': typeof SidebarResearchFinanceRoute
  '/simulator': typeof SidebarSimulatorRoute
  '/students': typeof SidebarStudentsRouteWithChildren
  '/tracker': typeof SidebarTrackerRoute
  '/trends': typeof SidebarTrendsRoute
  '/students/$studentId': typeof SidebarStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor-agent': typeof SidebarAdvisorAgentRoute
  '/ai-actions': typeof SidebarAiActionsRoute
  '/alerts': typeof SidebarAlertsRoute
  '/analytics': typeof SidebarAnalyticsRoute
  '/copilot': typeof SidebarCopilotRoute
  '/courses': typeof SidebarCoursesRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/enrollment-finance': typeof SidebarEnrollmentFinanceRoute
  '/faculty': typeof SidebarFacultyRoute
  '/finance': typeof SidebarFinanceRoute
  '/finance-actions': typeof SidebarFinanceActionsRoute
  '/finance-copilot': typeof SidebarFinanceCopilotRoute
  '/financial-health': typeof SidebarFinancialHealthRoute
  '/governance': typeof SidebarGovernanceRoute
  '/intervention': typeof SidebarInterventionRoute
  '/outcomes': typeof SidebarOutcomesRoute
  '/platform': typeof SidebarPlatformRoute
  '/profile': typeof SidebarProfileRoute
  '/research-finance': typeof SidebarResearchFinanceRoute
  '/simulator': typeof SidebarSimulatorRoute
  '/students': typeof SidebarStudentsRouteWithChildren
  '/tracker': typeof SidebarTrackerRoute
  '/trends': typeof SidebarTrendsRoute
  '/students/$studentId': typeof SidebarStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/advisor-agent': typeof SidebarAdvisorAgentRoute
  '/_sidebar/ai-actions': typeof SidebarAiActionsRoute
  '/_sidebar/alerts': typeof SidebarAlertsRoute
  '/_sidebar/analytics': typeof SidebarAnalyticsRoute
  '/_sidebar/copilot': typeof SidebarCopilotRoute
  '/_sidebar/courses': typeof SidebarCoursesRoute
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/enrollment-finance': typeof SidebarEnrollmentFinanceRoute
  '/_sidebar/faculty': typeof SidebarFacultyRoute
  '/_sidebar/finance': typeof SidebarFinanceRoute
  '/_sidebar/finance-actions': typeof SidebarFinanceActionsRoute
  '/_sidebar/finance-copilot': typeof SidebarFinanceCopilotRoute
  '/_sidebar/financial-health': typeof SidebarFinancialHealthRoute
  '/_sidebar/governance': typeof SidebarGovernanceRoute
  '/_sidebar/intervention': typeof SidebarInterventionRoute
  '/_sidebar/outcomes': typeof SidebarOutcomesRoute
  '/_sidebar/platform': typeof SidebarPlatformRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/research-finance': typeof SidebarResearchFinanceRoute
  '/_sidebar/simulator': typeof SidebarSimulatorRoute
  '/_sidebar/students': typeof SidebarStudentsRouteWithChildren
  '/_sidebar/tracker': typeof SidebarTrackerRoute
  '/_sidebar/trends': typeof SidebarTrendsRoute
  '/_sidebar/students/$studentId': typeof SidebarStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor-agent'
    | '/ai-actions'
    | '/alerts'
    | '/analytics'
    | '/copilot'
    | '/courses'
    | '/dashboard'
    | '/enrollment-finance'
    | '/faculty'
    | '/finance'
    | '/finance-actions'
    | '/finance-copilot'
    | '/financial-health'
    | '/governance'
    | '/intervention'
    | '/outcomes'
    | '/platform'
    | '/profile'
    | '/research-finance'
    | '/simulator'
    | '/students'
    | '/tracker'
    | '/trends'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor-agent'
    | '/ai-actions'
    | '/alerts'
    | '/analytics'
    | '/copilot'
    | '/courses'
    | '/dashboard'
    | '/enrollment-finance'
    | '/faculty'
    | '/finance'
    | '/finance-actions'
    | '/finance-copilot'
    | '/financial-health'
    | '/governance'
    | '/intervention'
    | '/outcomes'
    | '/platform'
    | '/profile'
    | '/research-finance'
    | '/simulator'
    | '/students'
    | '/tracker'
    | '/trends'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/advisor-agent'
    | '/_sidebar/ai-actions'
    | '/_sidebar/alerts'
    | '/_sidebar/analytics'
    | '/_sidebar/copilot'
    | '/_sidebar/courses'
    | '/_sidebar/dashboard'
    | '/_sidebar/enrollment-finance'
    | '/_sidebar/faculty'
    | '/_sidebar/finance'
    | '/_sidebar/finance-actions'
    | '/_sidebar/finance-copilot'
    | '/_sidebar/financial-health'
    | '/_sidebar/governance'
    | '/_sidebar/intervention'
    | '/_sidebar/outcomes'
    | '/_sidebar/platform'
    | '/_sidebar/profile'
    | '/_sidebar/research-finance'
    | '/_sidebar/simulator'
    | '/_sidebar/students'
    | '/_sidebar/tracker'
    | '/_sidebar/trends'
    | '/_sidebar/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/trends': {
      id: '/_sidebar/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof SidebarTrendsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/tracker': {
      id: '/_sidebar/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof SidebarTrackerRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/students': {
      id: '/_sidebar/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof SidebarStudentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/simulator': {
      id: '/_sidebar/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SidebarSimulatorRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/research-finance': {
      id: '/_sidebar/research-finance'
      path: '/research-finance'
      fullPath: '/research-finance'
      preLoaderRoute: typeof SidebarResearchFinanceRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/platform': {
      id: '/_sidebar/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof SidebarPlatformRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/outcomes': {
      id: '/_sidebar/outcomes'
      path: '/outcomes'
      fullPath: '/outcomes'
      preLoaderRoute: typeof SidebarOutcomesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/intervention': {
      id: '/_sidebar/intervention'
      path: '/intervention'
      fullPath: '/intervention'
      preLoaderRoute: typeof SidebarInterventionRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/governance': {
      id: '/_sidebar/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof SidebarGovernanceRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/financial-health': {
      id: '/_sidebar/financial-health'
      path: '/financial-health'
      fullPath: '/financial-health'
      preLoaderRoute: typeof SidebarFinancialHealthRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/finance-copilot': {
      id: '/_sidebar/finance-copilot'
      path: '/finance-copilot'
      fullPath: '/finance-copilot'
      preLoaderRoute: typeof SidebarFinanceCopilotRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/finance-actions': {
      id: '/_sidebar/finance-actions'
      path: '/finance-actions'
      fullPath: '/finance-actions'
      preLoaderRoute: typeof SidebarFinanceActionsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/finance': {
      id: '/_sidebar/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof SidebarFinanceRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/faculty': {
      id: '/_sidebar/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof SidebarFacultyRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/enrollment-finance': {
      id: '/_sidebar/enrollment-finance'
      path: '/enrollment-finance'
      fullPath: '/enrollment-finance'
      preLoaderRoute: typeof SidebarEnrollmentFinanceRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/courses': {
      id: '/_sidebar/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof SidebarCoursesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/copilot': {
      id: '/_sidebar/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof SidebarCopilotRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/analytics': {
      id: '/_sidebar/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof SidebarAnalyticsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/alerts': {
      id: '/_sidebar/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof SidebarAlertsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/ai-actions': {
      id: '/_sidebar/ai-actions'
      path: '/ai-actions'
      fullPath: '/ai-actions'
      preLoaderRoute: typeof SidebarAiActionsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/advisor-agent': {
      id: '/_sidebar/advisor-agent'
      path: '/advisor-agent'
      fullPath: '/advisor-agent'
      preLoaderRoute: typeof SidebarAdvisorAgentRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/students/$studentId': {
      id: '/_sidebar/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof SidebarStudentsStudentIdRouteImport
      parentRoute: typeof SidebarStudentsRoute
    }
  }
}

interface SidebarStudentsRouteChildren {
  SidebarStudentsStudentIdRoute: typeof SidebarStudentsStudentIdRoute
}

const SidebarStudentsRouteChildren: SidebarStudentsRouteChildren = {
  SidebarStudentsStudentIdRoute: SidebarStudentsStudentIdRoute,
}

const SidebarStudentsRouteWithChildren = SidebarStudentsRoute._addFileChildren(
  SidebarStudentsRouteChildren,
)

interface SidebarRouteRouteChildren {
  SidebarAdvisorAgentRoute: typeof SidebarAdvisorAgentRoute
  SidebarAiActionsRoute: typeof SidebarAiActionsRoute
  SidebarAlertsRoute: typeof SidebarAlertsRoute
  SidebarAnalyticsRoute: typeof SidebarAnalyticsRoute
  SidebarCopilotRoute: typeof SidebarCopilotRoute
  SidebarCoursesRoute: typeof SidebarCoursesRoute
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarEnrollmentFinanceRoute: typeof SidebarEnrollmentFinanceRoute
  SidebarFacultyRoute: typeof SidebarFacultyRoute
  SidebarFinanceRoute: typeof SidebarFinanceRoute
  SidebarFinanceActionsRoute: typeof SidebarFinanceActionsRoute
  SidebarFinanceCopilotRoute: typeof SidebarFinanceCopilotRoute
  SidebarFinancialHealthRoute: typeof SidebarFinancialHealthRoute
  SidebarGovernanceRoute: typeof SidebarGovernanceRoute
  SidebarInterventionRoute: typeof SidebarInterventionRoute
  SidebarOutcomesRoute: typeof SidebarOutcomesRoute
  SidebarPlatformRoute: typeof SidebarPlatformRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarResearchFinanceRoute: typeof SidebarResearchFinanceRoute
  SidebarSimulatorRoute: typeof SidebarSimulatorRoute
  SidebarStudentsRoute: typeof SidebarStudentsRouteWithChildren
  SidebarTrackerRoute: typeof SidebarTrackerRoute
  SidebarTrendsRoute: typeof SidebarTrendsRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarAdvisorAgentRoute: SidebarAdvisorAgentRoute,
  SidebarAiActionsRoute: SidebarAiActionsRoute,
  SidebarAlertsRoute: SidebarAlertsRoute,
  SidebarAnalyticsRoute: SidebarAnalyticsRoute,
  SidebarCopilotRoute: SidebarCopilotRoute,
  SidebarCoursesRoute: SidebarCoursesRoute,
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarEnrollmentFinanceRoute: SidebarEnrollmentFinanceRoute,
  SidebarFacultyRoute: SidebarFacultyRoute,
  SidebarFinanceRoute: SidebarFinanceRoute,
  SidebarFinanceActionsRoute: SidebarFinanceActionsRoute,
  SidebarFinanceCopilotRoute: SidebarFinanceCopilotRoute,
  SidebarFinancialHealthRoute: SidebarFinancialHealthRoute,
  SidebarGovernanceRoute: SidebarGovernanceRoute,
  SidebarInterventionRoute: SidebarInterventionRoute,
  SidebarOutcomesRoute: SidebarOutcomesRoute,
  SidebarPlatformRoute: SidebarPlatformRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarResearchFinanceRoute: SidebarResearchFinanceRoute,
  SidebarSimulatorRoute: SidebarSimulatorRoute,
  SidebarStudentsRoute: SidebarStudentsRouteWithChildren,
  SidebarTrackerRoute: SidebarTrackerRoute,
  SidebarTrendsRoute: SidebarTrendsRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
